# Generated by Django 4.0.4 on 2022-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectoequiposfallas',
            old_name='equipo',
            new_name='equipo_id',
        ),
        migrations.RenameField(
            model_name='proyectoequiposfallas',
            old_name='falla',
            new_name='falla_id',
        ),
        migrations.RenameField(
            model_name='proyectoequiposfallas',
            old_name='proyecto',
            new_name='proyecto_id',
        ),
    ]
