# Generated by Django 4.0.4 on 2022-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField()),
                ('funcion', models.CharField(blank=True, max_length=255)),
                ('criticidad', models.IntegerField()),
                ('ubicacion_tecnica', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
    ]
