# Generated by Django 4.0.4 on 2022-07-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrategia', '0001_initial'),
        ('especialidad', '0001_initial'),
        ('tiempo', '0001_initial'),
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_funcional', models.CharField(max_length=255)),
                ('modo_falla', models.CharField(max_length=255)),
                ('causas', models.CharField(max_length=255)),
                ('efecto_modo_falla', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('parametros', models.CharField(max_length=255)),
                ('repuesto', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('tiempo', models.IntegerField()),
                ('personas', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('procedimiento_seguridad', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad_id', models.ForeignKey(db_column='especialidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='especialidad_list', to='especialidad.especialidad')),
                ('estrategia_id', models.ForeignKey(db_column='estrategia_id', on_delete=django.db.models.deletion.CASCADE, related_name='estrategia_list', to='estrategia.estrategia')),
                ('maquina_id', models.ForeignKey(db_column='maquina_id', on_delete=django.db.models.deletion.CASCADE, related_name='falla_list', to='maquina.maquina')),
                ('medida_frecuencia_id', models.ForeignKey(db_column='medida_frecuencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='medida_list', to='tiempo.tiempo')),
                ('medida_tiempo_id', models.ForeignKey(db_column='medida_tiempo_id', on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_list', to='tiempo.tiempo')),
            ],
            options={
                'db_table': 'falla_tarea',
            },
        ),
    ]
