# Generated by Django 4.0.4 on 2022-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falla',
            old_name='maquina',
            new_name='maquina_id',
        ),
    ]
