# Generated by Django 4.0.4 on 2022-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('clasificacion', '0001_initial'),
        ('identificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impacto', models.CharField(max_length=255)),
                ('solucion_propuesta', models.CharField(max_length=255)),
                ('riesgo', models.IntegerField()),
                ('nivel_esfuerzo', models.IntegerField()),
                ('nivel_beneficio', models.IntegerField()),
                ('fecha_espera_solucion', models.DateField()),
                ('alcance', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clasificacion_id', models.ForeignKey(db_column='clasificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_list_ev', to='clasificacion.clasificacion')),
                ('identificacion_id', models.ForeignKey(db_column='identificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='identificacion_list_ev', to='identificacion.identificacion')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_list_ev', to='status.status')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
    ]
