# Generated by Django 4.0.4 on 2022-07-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('falla', '0001_initial'),
        ('tiempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_accion_secundaria', models.CharField(max_length=255)),
                ('duracion_trabajo', models.IntegerField()),
                ('personas', models.IntegerField()),
                ('repuesto', models.CharField(max_length=255)),
                ('descripcion_repuesto', models.CharField(max_length=255)),
                ('procedimiento_trabajo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('falla_id', models.ForeignKey(db_column='falla_id', on_delete=django.db.models.deletion.CASCADE, related_name='tarea_falla_list', to='falla.falla')),
                ('medida_tiempo_id', models.OneToOneField(db_column='medida_tiempo_id', on_delete=django.db.models.deletion.CASCADE, related_name='tarea_tiempo_list', to='tiempo.tiempo')),
            ],
            options={
                'db_table': 'tarea_secundario',
            },
        ),
    ]
