# Generated by Django 4.0.4 on 2022-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='area',
            name='proyecto',
            field=models.ManyToManyField(to='proyecto.proyecto'),
        ),
    ]
