# Generated by Django 4.0.4 on 2022-06-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('area', '0002_remove_area_proyecto_area_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='proyecto',
            field=models.ManyToManyField(related_name='area_list', to='proyecto.proyecto'),
        ),
    ]
