# Generated by Django 4.0.4 on 2022-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('area', '0003_alter_area_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='proyecto',
            field=models.ManyToManyField(related_name='proyecto_list', to='proyecto.proyecto'),
        ),
    ]
