# Generated by Django 4.0.4 on 2022-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobador', models.CharField(max_length=255)),
                ('fecha_aprobacion', models.DateField()),
                ('asignado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluacion_id', models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_list_apro', to='evaluacion.evaluacion')),
            ],
            options={
                'db_table': 'aprobacion',
            },
        ),
    ]
