# Generated by Django 4.0.4 on 2022-07-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='sigla',
            new_name='siglas',
        ),
    ]
