# Generated by Django 4.0.4 on 2022-06-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_modo_falla', models.CharField(max_length=255)),
                ('ds_efecto_falla', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaFmeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fmeca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmeca.fmeca')),
                ('maquina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.maquina')),
            ],
        ),
    ]
