# Generated by Django 4.0.4 on 2022-06-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoFmeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='FMeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_modo_falla', models.CharField(max_length=255)),
                ('ds_efecto_falla', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ManyToManyField(related_name='fallas_equipo', through='fmeca.EquipoFmeca', to='equipos.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipofmeca',
            name='fmeca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmeca.fmeca'),
        ),
    ]
