# Generated by Django 4.0.4 on 2022-06-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ManyToManyField(related_name='machine_list', through='equipos.AreaEquipo', to='area.area')),
            ],
        ),
        migrations.AddField(
            model_name='areaequipo',
            name='equipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
    ]
