# Generated by Django 4.0.4 on 2022-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
