# Generated by Django 4.0.4 on 2022-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_codigo_equipo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
