# Generated by Django 4.0.4 on 2022-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_alter_area_proyecto'),
        ('equipos', '0002_remove_equipo_area_equipo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='area',
            field=models.ManyToManyField(related_name='machine_list', to='area.area'),
        ),
    ]
