# Generated by Django 4.0.4 on 2022-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('aprobacion', '0001_initial'),
        ('evaluacion', '0001_initial'),
        ('identificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.CharField(max_length=255)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_estimado_termino', models.DateField()),
                ('overdue', models.IntegerField()),
                ('avance', models.IntegerField()),
                ('issues', models.CharField(max_length=255)),
                ('asignado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobacion_id', models.ForeignKey(db_column='aprobacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion_list_se', to='aprobacion.aprobacion')),
                ('evaluacion_id', models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_list_se', to='evaluacion.evaluacion')),
                ('identificacion_id', models.ForeignKey(db_column='identificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='identificacion_list_se', to='identificacion.identificacion')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_list_se', to='status.status')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
    ]
