# Generated by Django 4.0.4 on 2022-08-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('aprobacion', '0001_initial'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='aprobacion_id',
            field=models.ForeignKey(blank=True, db_column='aprobacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion_list_se', to='aprobacion.aprobacion'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='evaluacion_id',
            field=models.ForeignKey(blank=True, db_column='evaluacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_list_se', to='evaluacion.evaluacion'),
        ),
    ]
