# Generated by Django 4.0.4 on 2022-07-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposCompletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('machine_type', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('funcion_equipo', models.TextField()),
                ('falla_funcional', models.TextField()),
                ('ds_modo_falla', models.CharField(max_length=255)),
                ('ds_efecto_modo_falla', models.CharField(max_length=255)),
                ('descripcion_tarea', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipo_completos',
            },
        ),
    ]
