# Generated by Django 4.0.4 on 2022-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origen', '0001_initial'),
        ('clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('originador', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('tag_descripcion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clasificacion_id', models.ForeignKey(db_column='clasificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_list_ide', to='clasificacion.clasificacion')),
                ('origen_id', models.ForeignKey(db_column='origen_id', on_delete=django.db.models.deletion.CASCADE, related_name='origen_list_ide', to='origen.origen')),
            ],
            options={
                'db_table': 'identificacion',
            },
        ),
    ]
