# Generated by Django 4.0.4 on 2022-06-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('machine_type', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('funcion_equipo', models.CharField(blank=True, max_length=255)),
                ('falla_funcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('maquina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.maquina')),
            ],
        ),
    ]
