# Generated by Django 4.0.4 on 2022-07-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='codigo',
        ),
    ]
